api.curator.massopen.cloud.              7200 A  192.12.185.171
lb.curator.massopen.cloud.               7200 A  192.12.185.173
ns1.curator.massopen.cloud.              7200 A  192.12.185.172
apps.curator.massopen.cloud.             7200 A  192.12.185.173
apps.curator.massopen.cloud.             7200 NS ns1.curator.massopen.cloud.

provisioner-ipmi.curator.massopen.cloud. 7200 A  10.0.15.29
provisioner.curator.massopen.cloud.      7200 A  192.12.185.170

os-ctrl-0-ipmi.curator.massopen.cloud.   7200 A  10.0.15.5
os-ctrl-0.curator.massopen.cloud.        7200 A  192.12.185.175
os-ctrl-1-ipmi.curator.massopen.cloud.   7200 A  10.0.3.5
os-ctrl-1.curator.massopen.cloud.        7200 A  192.12.185.176
os-ctrl-2-ipmi.curator.massopen.cloud.   7200 A  10.0.5.7
os-ctrl-2.curator.massopen.cloud.        7200 A  192.12.185.177
