api.moc-infra.massopen.cloud.              7200 A  192.12.185.141
lb.moc-infra.massopen.cloud.               7200 A  192.12.185.143
ns1.moc-infra.massopen.cloud.              7200 A  192.12.185.142
apps.moc-infra.massopen.cloud.             7200 A  192.12.185.143
apps.moc-infra.massopen.cloud.             7200 NS ns1.moc-infra.massopen.cloud.

provisioner-ipmi.moc-infra.massopen.cloud. 7200 A  10.0.5.13
provisioner.moc-infra.massopen.cloud.      7200 A  192.12.185.140

os-ctrl-0-ipmi.moc-infra.massopen.cloud.   7200 A  10.0.15.2
os-ctrl-0.moc-infra.massopen.cloud.        7200 A  192.12.185.145
os-ctrl-1-ipmi.moc-infra.massopen.cloud.   7200 A  10.0.17.36
os-ctrl-1.moc-infra.massopen.cloud.        7200 A  192.12.185.146
os-ctrl-2-ipmi.moc-infra.massopen.cloud.   7200 A  10.0.3.6
os-ctrl-2.moc-infra.massopen.cloud.        7200 A  192.12.185.147
