api.zero.massopen.cloud.              7200 A  192.12.185.104
lb.zero.massopen.cloud.               7200 A  192.12.185.105
ns1.zero.massopen.cloud.              7200 A  192.12.185.106
apps.zero.massopen.cloud.             7200 A  192.12.185.105
apps.zero.massopen.cloud.             7200 NS ns1.zero.massopen.cloud.

provisioner-ipmi.zero.massopen.cloud. 7200 A  10.0.17.25
provisioner.zero.massopen.cloud.      7200 A  192.12.185.103

os-ctrl-0-ipmi.zero.massopen.cloud.   7200 A  10.0.17.34
os-ctrl-0.zero.massopen.cloud.        7200 A  192.12.185.110
os-ctrl-1-ipmi.zero.massopen.cloud.   7200 A  10.0.3.13
os-ctrl-1.zero.massopen.cloud.        7200 A  192.12.185.111
os-ctrl-2-ipmi.zero.massopen.cloud.   7200 A  10.0.5.12
os-ctrl-2.zero.massopen.cloud.        7200 A  192.12.185.112
os-sto-0-ipmi.zero.massopen.cloud.    7200 A  10.0.3.10
os-sto-0.zero.massopen.cloud.         7200 A  192.12.185.130
os-sto-1-ipmi.zero.massopen.cloud.    7200 A  10.0.19.34
os-sto-1.zero.massopen.cloud.         7200 A  192.12.185.131
os-sto-2-ipmi.zero.massopen.cloud.    7200 A  10.0.19.38
os-sto-2.zero.massopen.cloud.         7200 A  192.12.185.132
os-wrk-0-ipmi.zero.massopen.cloud.    7200 A  10.0.15.11
os-wrk-0.zero.massopen.cloud.         7200 A  192.12.185.115
os-wrk-1-ipmi.zero.massopen.cloud.    7200 A  10.0.3.12
os-wrk-1.zero.massopen.cloud.         7200 A  192.12.185.116
os-wrk-2-ipmi.zero.massopen.cloud.    7200 A  10.0.17.35
os-wrk-2.zero.massopen.cloud.         7200 A  192.12.185.117
